// amwall — WFP provider primitive.
// Copyright (C) 2026  amwall contributors. Licensed GPL-3.0-or-later.
//
// Wraps `FwpmProviderAdd0`. A provider is the identity of the entity
// that owns filters / sublayers in WFP — typically one per running
// application. Upstream simplewall registers a single non-persistent
// provider per session.

use windows::Win32::NetworkManagement::WindowsFilteringPlatform::{
    FWPM_DISPLAY_DATA0, FWPM_PROVIDER0, FWPM_PROVIDER_FLAG_PERSISTENT, FwpmProviderAdd0,
};
use windows::Win32::Security::PSECURITY_DESCRIPTOR;
use windows::Win32::System::Rpc::UuidCreate;
use windows::core::{GUID, PWSTR};

use super::{ERROR_SUCCESS, WfpEngine, WfpError};

/// `FWP_E_ALREADY_EXISTS` — returned by `FwpmProviderAdd0` when a
/// provider with the given key already exists in the kernel. Treated
/// as a soft-success by `add_with_key` (re-install path).
const FWP_E_ALREADY_EXISTS: u32 = 0x8032_0009;

/// Handle to a registered WFP provider. Holds the GUID assigned at
/// `add()` time; sublayers and filters reference this key to identify
/// themselves as belonging to this provider.
///
/// The provider itself is volatile (no `FWPM_PROVIDER_FLAG_PERSISTENT`),
/// so the kernel removes it automatically when the engine session
/// ends — including when `WfpEngine` is dropped or the process exits.
/// No explicit `Drop` impl on this type.
#[derive(Debug, Clone, Copy)]
pub struct Provider {
    key: GUID,
}

impl Provider {
    /// The provider's GUID, generated by `UuidCreate` at `add()` time.
    pub fn key(&self) -> GUID {
        self.key
    }
}

/// Register a new provider with the given engine.
///
/// Calls `FwpmProviderAdd0(engine, &provider, NULL)` after generating
/// a fresh `providerKey` GUID and populating `displayData.name` /
/// `displayData.description`. Requires the caller to be elevated;
/// on a non-admin process this returns `WfpError::ProviderAdd(5)`
/// (`ERROR_ACCESS_DENIED`).
///
/// `persistent = false` registers a session-scoped provider that
/// the kernel removes when the engine session ends (or on next
/// reboot if the session leaks). `persistent = true` sets
/// `FWPM_PROVIDER_FLAG_PERSISTENT`, which makes the provider
/// survive across reboots — needed for the upstream-style
/// `simplewall -install` flow where rules persist after the CLI
/// exits.
pub fn add(
    engine: &WfpEngine,
    name: &str,
    description: &str,
    persistent: bool,
) -> Result<Provider, WfpError> {
    let mut key = GUID::zeroed();
    let rpc_status = unsafe { UuidCreate(&mut key) };
    if rpc_status.0 != 0 {
        return Err(WfpError::UuidCreate(rpc_status.0));
    }

    // Display strings live in this stack frame for the duration of
    // FwpmProviderAdd0; the kernel copies them into its own storage
    // before returning.
    let mut name_buf: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
    let mut desc_buf: Vec<u16> = description
        .encode_utf16()
        .chain(std::iter::once(0))
        .collect();

    let mut provider: FWPM_PROVIDER0 = unsafe { std::mem::zeroed() };
    provider.providerKey = key;
    provider.displayData = FWPM_DISPLAY_DATA0 {
        name: PWSTR(name_buf.as_mut_ptr()),
        description: PWSTR(desc_buf.as_mut_ptr()),
    };
    if persistent {
        provider.flags = FWPM_PROVIDER_FLAG_PERSISTENT;
    }
    // providerData / serviceName stay zero.

    let status = unsafe {
        FwpmProviderAdd0(
            engine.raw(),
            &provider,
            PSECURITY_DESCRIPTOR(std::ptr::null_mut()),
        )
    };
    drop(name_buf);
    drop(desc_buf);

    if status != ERROR_SUCCESS {
        return Err(WfpError::ProviderAdd(status));
    }
    Ok(Provider { key })
}

/// Like `add` but uses a caller-provided `providerKey` instead of
/// generating one with `UuidCreate`. Tolerates
/// `FWP_E_ALREADY_EXISTS` (returns Ok with the given key) so a
/// re-run of `amwall -install` doesn't fail when the
/// previous install's persistent provider is still in the kernel.
///
/// Use this for the upstream-style "well-known provider GUID"
/// install pattern; use `add` when the caller wants a fresh
/// session-scoped provider with no key-collision risk.
pub fn add_with_key(
    engine: &WfpEngine,
    name: &str,
    description: &str,
    persistent: bool,
    key: &GUID,
) -> Result<Provider, WfpError> {
    let mut name_buf: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
    let mut desc_buf: Vec<u16> = description
        .encode_utf16()
        .chain(std::iter::once(0))
        .collect();

    let mut provider: FWPM_PROVIDER0 = unsafe { std::mem::zeroed() };
    provider.providerKey = *key;
    provider.displayData = FWPM_DISPLAY_DATA0 {
        name: PWSTR(name_buf.as_mut_ptr()),
        description: PWSTR(desc_buf.as_mut_ptr()),
    };
    if persistent {
        provider.flags = FWPM_PROVIDER_FLAG_PERSISTENT;
    }

    let status = unsafe {
        FwpmProviderAdd0(
            engine.raw(),
            &provider,
            PSECURITY_DESCRIPTOR(std::ptr::null_mut()),
        )
    };
    drop(name_buf);
    drop(desc_buf);

    match status {
        ERROR_SUCCESS | FWP_E_ALREADY_EXISTS => Ok(Provider { key: *key }),
        other => Err(WfpError::ProviderAdd(other)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Live admin-only smoke test. Requires:
    ///
    /// - the calling shell is elevated (Run as Administrator)
    /// - the BFE service is running
    ///
    /// Run with `cargo test -- --ignored` from an elevated shell.
    #[test]
    #[ignore = "requires elevated shell to call FwpmProviderAdd0"]
    fn add_provider_admin_smoke() {
        let engine = WfpEngine::open().expect("engine open failed");
        let provider = add(&engine, "amwall test", "test provider", false)
            .expect("FwpmProviderAdd0 failed");
        let key = provider.key();
        assert_ne!(
            (key.data1, key.data2, key.data3, key.data4),
            (0, 0, 0, [0u8; 8]),
            "provider key was nil GUID"
        );
        // Explicit cleanup (engine-drop cleanup is unreliable in the
        // test runner; see M1.7).
        engine.cleanup_provider(&key).expect("cleanup_provider failed");
    }
}
